save_dir: ./saved_models
save_name: cifar10_40_0_IN100
resume: False
load_path: None
overwrite: True
use_tensorboard: True
ubl_data_dir: /scratch/a/amiilab/shuvendu/data/imagenet100
ubl_dataset: ImageNet100
num_train_iter: 1048576
num_eval_iter: 1000
num_labels: 40
batch_size: 64
eval_batch_size: 1024
alpha: 0.1
w_rot: 10
warm_up: 0.015
uratio: 1
projection_head: mlp
dim_in: 128
feat_dim: 128
ema_m: 0.999
optim: SGD
lr: 0.0075
momentum: 0.9
weight_decay: 0.0005
amp: False
net: WideResNet
net_from_name: False
depth: 28
widen_factor: 2
leaky_slope: 0.1
dropout: 0.0
data_dir: ./data
dataset: cifar10
train_sampler: RandomSampler
num_classes: 10
num_workers: 1
alg: unmixmatch
seed: 0
world_size: 1
rank: 0
gpu: 'cuda:0'
w_contrastive: 0.1
algo_class: unmixmatch
id: E4_P2_0
